// Copyright (c) 2022 Katie G All rights reserved.
//
// Created by: Katie G
// Date: October 11th, 2022
// This program makes the user guess
// a random number generated by the
// program, then checks to see if that number
// is the same as the one the program
// generated.The program then displays
// the result back to the user.
#include <random>
#include <iostream>

// this function gets the user's guess,
// generates a random number, then checks
// to see if it is equal to the user's num.
// The function then displays the result
// to the user.
int main() {
    // initializing the variables to hold
    // user guess and generated number.
    int userGuess, generatedNum;

    // program generates random num from 0-9.
    std::random_device rseed;

    std::mt19937 rgen(rseed());

    std::uniform_int_distribution<int> idist(0, 9);

    // setting the random number to the variable.
    generatedNum = idist(rgen);

    // getting user's guess.
    std::cout << "My little friend has generated a random number between 0-9. ";
    std::cout << "Guess what it is :) ";
    std::cin >> userGuess;

    // checks to see if user guess is equal to generated num.
    // if so, prints "you got it right". else, prints
    // "you did not get it right".
    if (userGuess == generatedNum) {
        std::cout << "\n";
        std::cout << "You got it right! Well done :)\n";
    } else {
        std::cout << "\n";
        std::cout << "You did not get it right :(\n";
    }
}
